### ISSUE TITLE
Running program

### ISSUE THREAD

**Issue by User-790** [D3Ext/WEF#11]
Hi there, I have followed all the steps and I was just a little skeptical from the presentation of what it provided me. (I am just comparing from the photos in the presentation to my computer and actual result). I have also been having difficulty identifying my interface as well.
![Kali img](https://user-images.githubusercontent.com/90978354/182643201-9c199ad8-0667-41ed-adef-c9f54c857ad9.png)

**Comment by D3Ext** [comment]
Hi, I changed a little bit the help panel but it shouldn't change nothing, what's your problem? Do you know how to see the name of the interface?
The common usage of the program should be like this:
```sh
wef -i wlan0
```

**Comment by User-790** [comment]
Yes, mostly the interface was my problem, but thank you for your response! I'll take a look at the help panel more carefully. 
Thank you again!

**Comment by D3Ext** [comment]
Ok, try to use it with your network card and tell me what happens
In my case I have an Alfa AWUS036ACM antenna which supports 2,4Ghz and 5Ghz and it works really well, however it should work with all the antennas that accept monitor mode
