### ISSUE TITLE
porta cautivo

### ISSUE THREAD

**Issue by 01-VOS-01** [D3Ext/WEF#13]
al momento de crear un Evil Twin Attack
  en el dispositivo de la victima dice "conectado pero sin intenet"
y no  sale la notificacion del portal cautivo y aunque intente abrirlo desde el navegador no resulta 
mi tarjeta de red si admite modo monitor 
¿estoy haciendo algo mal?
¿tengo que tener una configuracion concreta para correrlo correctamente?
¿que hago para solucionarlo?
MUCHAS GRACIAS DE ANTICIPACION!

**Comment by D3Ext** [comment]
Pues en principio deberia ir bien, por si acaso asegurate de no tener el puerto 80 ocupado porque es donde el portal del login corre
Otra cosa, el punto de acceso que se genera no tiene conexión si se crea en una maquina virtual (no es un error del script, sino que no se puede hacer físicamente para enrutar la conexión), aun asi no lo he probado en un Kali o Parrot fisico y no se al 100% si tendría conexion

**Comment by D3Ext** [comment]
Que antena usas? Aun asi no creo que sea el problema
Y tampoco creo que estes haciendo nada mal, solo tienes que activar la tarjeta en modo monitor, darle al Evil Twin, y ponerle el nombre, el canal y la plantilla que quieras, solo con hacer eso ya deberia generarlo sin problemas
