### ISSUE TITLE
Setup Failure

### ISSUE THREAD

**Issue by ebolanoso** [D3Ext/WEF#14]
Hello,
I couldn't install WEF, here the error:

**[WEF] Preparing the setup for working properly,
Setup.sh: line 46: cd: too many arguments
sed: can't read /opt/wef/.wef.config: No such file or directory
sed: can't read /opt/wef/.wef.config: No such file or directory

[+] Installing some dependencies..setup.sh: line 131: cd: too many arguments**

Could you help me, please?

**Comment by D3Ext** [comment]
Hello, I checked the setup.sh and I think that it occurs because I have some commands without double quotes and if you change directory to a dir with spaces in its name the command gives errors, I'll fix it this today, thanka!

**Comment by ebolanoso** [comment]
Thanks, I'll be waiting.

**Comment by D3Ext** [comment]
Fixed, it should work now, tell me if it fails or whatever

**Comment by ebolanoso** [comment]
Same failure........ There is something rare, because I was testing in a Virtual Machine and it works properly, but when I try using a laptop with Kali it doesn't work, I don't know why.

[WEF] Preparing the setup for working properly.
./setup.sh: line 46: cd: /home/kali/github/05.: No such file or directory

**Comment by D3Ext** [comment]
Uuhmm I don't know why it happens but I added more timeout to do a couple of things of the setup so it may work now.
However I assume that you have basic commands like `find` or `dirname`, in my case I only tested the program in virtual machines
