### ISSUE TITLE
5Gghz

### ISSUE THREAD

**Issue by Jaymzu** [D3Ext/WEF#22]
Hey guys, 
I can't find any reference on how to run WEF in 5Ghz (even though the description mentions it's supported). Any idea where I should look?

Thanks

**Comment by D3Ext** [comment]
Hi, recently I noticed that I have to change some things to adapt the 5Ghz at 100%, so in the next days I will upload an update with more checks mainly in the deauth attack

**Comment by Jaymzu** [comment]
Sweet. Standing by ;)

**Comment by ultrazar** [comment]
From where I know, any attack that supports 5Ghz it applies it automatically according to the needed wlan channel. 
In the case it doesn't work properly, you can try to change it manually with `iwconfig wlan1 channel x`. Otherwise, specify exactly what isn't working.
