### ISSUE TITLE
Problem with "Evil Twin" on raspberry pi

### ISSUE THREAD

**Issue by ArtemSupa** [D3Ext/WEF#23]
At the moment of creating a fake Ap from the option 8 of the menu, it is created correctly, but the wifi network is not visible in the devices, I have tried with two wifi cards, the tplink Tl-WN722N and the Alfa AWUSS036NH and with none of them it works, it is important to emphasize that at no time of the process it shows me an error by console, simply at the moment of creating the fake ap the network does not appear in other devices.

Translated with www.DeepL.com/Translator (free version)

**Comment by ultrazar** [comment]
First, maybe the problem is in your installation so does any other attack like the deauthentication work?
Second, what's exactly the output that shows up in the console?
And finally which parameters did you enter?

(I'm the main maintainer of the evil twin in this repo)

**Comment by D3Ext** [comment]
I can't test the attack on a Raspberry but it works on my Parrot OS. What OS are you using?

**Comment by ArtemSupa** [comment]
1. Probare la desautenticacion y comentare que tal.
2. En consola no me aparece ningun error ni nada, sigue el proceso correctamente por consola.
3. Los parametros que siempre pongo es el nombre de la AP, el canal eh probado con todos, lo dejo sin contraseña y el portal cautivo que ocupo es google.

**Comment by D3Ext** [comment]
Vale, si el ataque de deauthenticacion funciona bien quizas sea un problema del Evil Twin, ya que es un tanto distinto porque tiene que iniciar ciertos procesos (para crear el AP) como el de **hostapd** y **dnsmasq**, pero al ser en un dispositivo headless quizas ocurra algun error

**Comment by ArtemSupa** [comment]
Estimado, probe con una version anterior, especificamente este commit (3fd817cf7f6e54248d705ef06db965db8a142462) y me funciono correctamente, pero volvi a probar con la ultima version y no funciona.

**Comment by D3Ext** [comment]
Vale, pues revisare que cambio y tratare de ver cual es el posible problema

**Comment by D3Ext** [comment]
Acabo de comprobar rapidamente los cambios que ha habido en el script desde el commit que mencionastes y por lo que veo no ha habido ningun cambio relacionado con ninguno de esos ataques

**Comment by ArtemSupa** [comment]
El de Evil Twin funciono en ese commit

**Comment by D3Ext** [comment]
Pues si no me equivoco no ha cambiado nada desde entonces... y el de deauthenticacion te funciona?

**Comment by D3Ext** [comment]
Quizas haya habido algun problema con la version del script al usar otro commit y demas. Creo que si pruebas a desinstalar WEF ejecutando el desinstalador y volviendolo a instalar desde el repositorio podria arreglar tu problema

**Comment by ArtemSupa** [comment]
Efectivamente, era eso, desinstale WEF con el desintalador y volví a clonar el repositorio, luego instale con setup.sh y volvio a funcionar con la ultima version, muchas gracias!!

**Comment by D3Ext** [comment]
Vale perfecto! :D
