### ISSUE TITLE
Link para descargar las herramientas no funciona.

### ISSUE THREAD

**Issue by savioazure** [D3Ext/WEF#24]
Hola, 
el link ofrecido en el curso de WI-FI para descargarse las herramientas necesarias no funciona:

https://raw.githubusercontent.com/D3Ext/d3ext.github.io/gh-pages/wifi-install.sh

gracias.

**Comment by D3Ext** [comment]
Gracias por comentar, hace poco hice cambios en la web y no he cambiado el link, lo cambio ahora mismo 😅👍

**Comment by D3Ext** [comment]
Deberia de funcionar sin problemas, muchas gracias por avisar :D

**Comment by savioazure** [comment]
Ahora funciona , gracias, 
aunque voy acabar echandole un vistazo al script  para instalarlo a mano pq al arrancarlo me salta el 
siguiente error: 
El sistema actual no esta basado en Debian, ejecuta este script en: Ubuntu, Parrot, Kali Linux...

**Comment by D3Ext** [comment]
Vale, pues luego lo pruebo de nuevo ek Kali Linux y veo si hay algun error para arreglarlo
