### ISSUE TITLE
$name variable causes script failure cascade if SSID has spaces or quotes in name

### ISSUE THREAD

**Issue by rmrf-sl4sh** [D3Ext/WEF#26]
See screenshot for example

![2023-01-15 07_14_12-Window](https://user-images.githubusercontent.com/79405840/212540119-22505e0c-354f-4469-949b-259b7ca7cdca.png)

**Comment by D3Ext** [comment]
Thank you for the issue, a few days ago I was improving the code and I noticed that in some parts of it the variables may cause some errors, I try to fix it ASAP. I also will fix the "DISPLAY" erros so in case it fails, it doesn't print any output.
