### ISSUE TITLE
"Trying to obtain IP address" of evil-twin AP.

### ISSUE THREAD

**Issue by 0z5** [D3Ext/WEF#27]
Hello,

I've been trying out your tool and while testing out Evil-Twin with the setting option 5, just AP, I've noticed that meanwhile an AP is created, my phone can't get the IP address of the fake AP while trying to log into it. My phone connects to the AP (successfully using the password) and stays in the "trying to get IP address" state and I can't see any connected devices in the terminal. 

My configuration for testing is:

My PC that creates a evil-twin AP (e.g. named Starbucksss) and internet access on usb0
My phone with an AP (e.g. named Starbucks) and internet tethering via USB connected to my PC
Another phone that tries to log into the evil-twin AP (Starbucksss in this case)

Is something wrong with my configuration? I'm afraid I don't know any Spanish as well, so I can't type in your native language, sorry about that. :(

Thank you!

**Comment by ultrazar** [comment]
In the first place, to perform this attack (as well as many others from this tool), you need a Wi-Fi adapter that supports monitor mode.
Secondly, the IP that your phone should get is something like `10.0.221.2`. If it doesn't work is probably a problem with routing or dnsmasq, this is common and different for each network setup. Also, make sure you have the latest version of WEF by just executing `setup.sh`. 

Make sure that when WEF asks for the interface to route traffic `[+] Interface to route internet through (default=eth0):` you actually type the correct interface (in this case usb0?).

I hope this may help. If not, you could give more info (e.g: logs like `/var/log`, `/var/log/syslog` for dnsmasq and hostapd )
