### ISSUE TITLE
Network card already in monitor mode but it doesn't work

### ISSUE THREAD

**Issue by fengzirock** [D3Ext/WEF#30]
![image](https://user-images.githubusercontent.com/59859409/236162471-ae523bc0-56bc-4e47-be1a-8cac93429122.png)

**Comment by D3Ext** [comment]
Please provide more information so I can help you

**Comment by fengzirock** [comment]
i use wsl ubuntu20.04 and network card like this
![image](https://user-images.githubusercontent.com/59859409/236369877-dffba207-3d9a-4d57-9618-6e9ddba888d8.png)
