### ISSUE TITLE
WEF Questions and Answers

### ISSUE THREAD

**Issue by Dex71** [D3Ext/WEF#34]
Hola estimado, estoy teniendo un problema que no me pasaba antes ( hace un año masomenos cuando lo probe )
Al querer usar el evil twin con portal cautivo me pide que coloque el handshake, antes no me lo solicitaba. 
Como se prosigue ?
gracias

**Comment by D3Ext** [comment]
Hola! En la ultima actualización de la herramienta cambié bastantes funciones para mejorar la mayoria de cosas, entre ellas el ataque EvilTwin em cual quise enfocarlo para la obtención de la contraseña de un AP legítimo, y para ello necesitamos un archivo .pcap que contenga un handshake válido del AP que se va a atacar para comprobar si la contraseña que la supuesta victima introduce, es válida por lo que habriamos obtenido la contraseña.

Si lo que quieres es levantar un AP con una template de portal cautivo como antes hacia la herramienta echale un ojo al directorio `lib/` que contiene los archivos de config de hostapd y dnsmasq para que los puedas modificarlos y editarlos.
