### ISSUE TITLE
HS - Evil Twin

### ISSUE THREAD

**Issue by IGSMORA** [D3Ext/WEF#35]
Saludos , soy un poco nuevo en todo este mundillo .
Al intentar usar la herramienta especificamente la funcion de evil twin llega el momento de seleccionar la ruta de un HS previo.
Al señalar la ruta , la herramienta me responde que el archivo no existe.
He probado con diferentes HS y la respuesta es la misma .
Uso el mismo HS en otros aplicativos y si los aceptan.

**Comment by D3Ext** [comment]
Hola, ¿podrias adjuntar un poco mas de información y a poder ser capturas de pantalla para detectar el posible fallo?

**Comment by IGSMORA** [comment]
![Screenshot_2023-10-08_08_09_34](https://github.com/D3Ext/WEF/assets/147275875/1b54d920-cb9c-4f08-8179-2aac8731150c)
![Screenshot_2023-10-08_08_10_24](https://github.com/D3Ext/WEF/assets/147275875/b943a02d-0294-4c71-b1d3-ea951c361e37)

**Comment by D3Ext** [comment]
¿Has probado a especificar la ruta del handshake sin las comillas? Deberia funcionar sin comillas y en el caso de que el archivo exista, por supuesto

**Comment by D3Ext** [comment]
El programa trata todas las strings de las formas mas seguras posibles para asegurarse de que no hay ningun error en cuanto a caracteres como " '/\.,& entre otros.

**Comment by IGSMORA** [comment]
gracias por responder amigo. La verdad no se que onda jij
![Screenshot_2023-10-08_12_58_57](https://github.com/D3Ext/WEF/assets/147275875/ebad276f-431d-4a21-af22-9007761eedc5)

**Comment by D3Ext** [comment]
¿Has comprobado si es asi y si funciona como deberia?

**Comment by IGSMORA** [comment]
Hola , acabo de probarlo y efectivamente esta funcionando... Muchas gracias por la paciencia y dedicación  .
