### ISSUE TITLE
PKMCID Attack Failes due to hcxdumptool error

### ISSUE THREAD

**Issue by DaKahuna** [D3Ext/WEF#38]
A change was made to the hcxdumptool which changed the output feature '-w' to '-o'.  WEF is still using the '-w' for writing the output file and this results in the error

[*] Starting PMKID attack, press Ctrl + C to stop it...
hcxdumptool: invalid option -- 'w'
hcxdumptool 6.2.5 (C) 2021 by ZeroBeat
usage: hcxdumptool -h for help

at which point the tool hangs. 

**WEF version**
wef v1.3 for linux (https://github.com/D3Ext/WEF)

**System information:**
Linux  6.5.0-17-generic #17~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan 16 14:32:32 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by painowest** [comment]
you need latest hcxdumptool (6.3.0+)

**Comment by D3Ext** [comment]
You are right @painowest, latest hcxdumptool version uses `-w` parameter to especify the output file. WEF works with latest versions of hcxdumptool
