### ISSUE TITLE
Problemas con la instalacion

### ISSUE THREAD

**Issue by furylow** [D3Ext/WEF#39]
Tengo problemas instalando WEF. 
Ejecuto las instrucciones pero no encuentro el instalador dentro de la carpeta, lo tengo en src
Cuando lo ejecuto me dice que no encuetra el repositorio, que intente ejecutarlo desde donde se ha clonado
gracias de antemano

**Comment by furylow** [comment]
cuando ejecuto setup.sh desde el directorio src me sale lo siguiente:
setup.sh: line 41: cd: $'\n/home/kali/WEF': No such file or directory

**Comment by D3Ext** [comment]
Creo que hay un pequeño error en la documentación ya que en la última actualización se cambio la forma de instalar WEF por lo que deberias poder instalar todo de forma normal con simplemente clonar el repositorio y despues ejecutando el archivo `wef`. Este se deberia encargar de todo en caso de que no se haya instalado antes.

De todas formas, si aún así experimentas errores, vuelve a comentar aquí mismo el error para solucionarlo

**Comment by furylow** [comment]
Muchas gracias por responder.
Mi error era bastante tonto, soy novato y pensaba que bash solo ejecutaba
los archivos .sh ,por eso buscaba setup.sh dentro de /src
Ahora ya se me ha instalado.
Un saludo

**Comment by D3Ext** [comment]
Gracias a ti por avisar del error en las instrucciones de instalación
