### ISSUE TITLE
Evil twin attack error

### ISSUE THREAD

**Issue by furylow** [D3Ext/WEF#40]
Hola
Cuando se ejecuta el Evil Twin Attack, con la opcion Rogue AP+ Captive Portal, obtengo el siguiente error en la terminal:
arp: option requires an argument --'i'

**Comment by D3Ext** [comment]
Hola de nuevo. He detectado la línea exacta en la que se produce el error pero necesitaría mas información para poder solucionarlo. Por favor vuelve a crear un issue de tipo reporte de un bug y proporciona la información necesaria para que te pueda ayudar. Para hacer esto debes hacer click en "Issues" y después a "Get started"

![imagen](https://github.com/D3Ext/WEF/assets/67125397/a3b325d3-2834-4834-906e-67954c5d3cf4)

**Comment by D3Ext** [comment]
Tambien sería util que compartas el output al ejecutar el comando `iw dev`
