### ISSUE TITLE
Best Wifi-Adapters that support most of the attacks?

Most affordable and Most expensive adapters.


### ISSUE THREAD

**Issue by rohanraj-aipro** [D3Ext/WEF#46]

**Comment by D3Ext** [comment]
This topic is already discussed in the Wiki. However, it is not about the supported attacks, if an adapter supports monitor mode then it will support all the attacks. There's only one exception, to perform the Evil Twin attack while deauthing the legit AP your adapter must support VIF (Virtual Interfaces). Anyway, this is also covered in the Wiki.

If you don't want to spend much money go for a cheap adapter. If you want to get a 100% original adapter which allows VIF and has better specifications, then go for an Alfa adapter from the original web store.
