### ISSUE TITLE
Kali Error

### ISSUE THREAD

**Issue by Burgess85** [D3Ext/WEF#7]
*] Starting Caffe-Latte attack...
timeout: invalid time interval ‘bash’
Try 'timeout --help' for more information.
Warning: This program is an suid-root program or is being run by the root
user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set
/usr/bin/wef: line 1280: kill: (14470) - No such process
[+] Caffe-Latte Attack completed
[*] Captures stored in: /opt/wef/main/captures

**Comment by D3Ext** [comment]
Thanks for your comment, ensure you are using the latest version because a few days ago I tested in depth the framework in Kali and there were errors so I think that with the latest version will work fine but I'll check it

**Comment by Burgess85** [comment]
I have only just installed and that was the error

**Comment by ultrazar** [comment]
Hey @Burgess85 the same happened to me when testing attacks that requires to open a new window in my headless installation of Kali Linux in a Rasberry Pi. 
Can you specify what's your working platform?

**Comment by Burgess85** [comment]
Headless raspberry pi using Kali and screen

**Comment by D3Ext** [comment]
I don't have a Raspberry so I can't test it but I can add a command/option inside the framework to headless raspberries to do the AP scanning in the same terminal to avoid using the screen. I think it would be a good option

**Comment by Burgess85** [comment]
Yes that should work

**Comment by D3Ext** [comment]
I'm working on a new update because if you use airodump-ng with a specific timeout in bash it doesn't run, so the people who use headless systems won't see the scan output until it finishes
