### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Sup3rY4k** [D3Ext/WEF#9]
I downloaded the software and it worked fine for a couple days now I cant get it to launch. i will type wef into the terminal and this is all i get...i type my interface and everything, nothing changes 
![wef error2](https://user-images.githubusercontent.com/103078718/179805788-817885db-cb1a-48cd-be3d-bd559e8736d6.png)
![wef error](https://user-images.githubusercontent.com/103078718/179805793-f49d6cf1-09c0-41ca-92fc-9134e9fa20c9.png)

**Comment by D3Ext** [comment]
As I see you pass the name of the interface before the -i argument. You should do something like this: wef -i wlan0

**Comment by Sup3rY4k** [comment]
thank you. that worked. I'm a dumbass

**Comment by D3Ext** [comment]
No problem, thank you for using WEF and I hope you enjoy it
